// Generated by Wrangler on Thu May 02 2024 13:11:16 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	kv: KVNamespace;
	logs: KVNamespace;
	maxLogLength: "100";
}
