#:schema node_modules/wrangler/config-schema.json
name = "olics"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "kv"
id = "3fee84b4ac6d4ede94d793a72423f39a"

[[send_email]]
name = "email"
destination_address = "olics@rmf.io"
